package consts

SCREEN_WIDTH :: 910
SCREEN_HEIGHT :: 610
SQUARE_SIZE :: 10
GRID_ROWS :: SCREEN_HEIGHT / SQUARE_SIZE
GRID_COLUMNS :: SCREEN_WIDTH / SQUARE_SIZE
GRID_SIZE :: GRID_ROWS * GRID_COLUMNS
TARGET_GENERAING_MAZE_FPS :: 360
TARGET_SOLVING_FPS :: 60
